### ISSUE TITLE
issue in PIC interrupt

### ISSUE THREAD

**Issue by nouragamall** [AbdelrahmanBadr22/G1_8bit_MCUs_Drivers#61]
at PR #60 can't add ISR Implement because the make file of pic
![image](https://github.com/AbdelrahmanBadr22/G1_8bit_MCUs_Drivers/assets/116299689/90f1948e-efe6-4f02-86f2-eb6c53ea97f5)

**Comment by ManarAbdelraouf** [comment]
@nouragamall 
The solution :
1) We must include <xc.h>
2) Syntax :  void __interrupt() ISR() {  }
3)Run xc compiler (still issue in Make file)

**Comment by AbdelrahmanBadr22** [comment]
Solved by @ManarAbdelraouf
