### ISSUE TITLE
Add stack implementation in utils directory 

### ISSUE THREAD

**Issue by AbdelrahmanBadr22** [AbdelrahmanBadr22/G1_8bit_MCUs_Drivers#76]
According to `Calculator` app, @noran97 has suggested to add the `stack` implementation to `utils/datastructure` to be easier to used in future applications.

**Comment by ManarAbdelraouf** [comment]
@AbdelrahmanBadr22 
I am already do this in my app 
C/DataStructure/Stack

**Comment by AbdelrahmanBadr22** [comment]
> @AbdelrahmanBadr22 I am already did this in my app C/DataStructure/Stack

Hi @ManarAbdelraouf <br>
The main purpose from this issue is to add a very generic stack implementation (new and improved version) to make something like a templates in `cpp`.

Consider the following situation:
We want to create two stacks one will hold `char` and the other will hold `uint32` in this case we should implement two stack with two different header files  e.g. 'charStack.h` and `intStack.h` and configure `STACK_TYPE` with type we want which is really something disturbing. We want to use only one generic stack to solve this situation :)

**Comment by AbdelrahmanBadr22** [comment]
duplicated
